export default {
  id: 'ielts-r-1',
  type: 'ielts',
  title: 'IELTS Reading Mock 1',
  duration: 60,
  parts: [
    {
      id: 'passage1',
      title: 'Passage 1 - The History of the Bicycle',
      instructions: 'Read the passage and answer questions 1-13.',
      type: 'passage',
      passages: [
        {
          title: 'The History of the Bicycle',
          content: 'The first bicycle-like machine was called the "dandy horse", invented by Baron Karl von Drais in 1817 in Germany. It was made of wood and had no pedals — riders pushed their feet against the ground.\n\nIn the 1860s, French inventors Pierre Michaux and Pierre Lallement added pedals to the front wheel, creating the "boneshaker". The name came from its rough ride on iron-rimmed wheels over cobblestone roads. In the 1870s, the "penny-farthing" appeared with a huge front wheel and a small rear wheel. These were fast but dangerous.\n\nThe modern bicycle arrived in 1885 when John Kemp Starley invented the "safety bicycle". It used a chain to drive the rear wheel, making it much safer. In 1888, John Dunlop invented pneumatic (air-filled) tires, which made cycling far more comfortable.',
          questions: [
            { id: 1, type: 'mcq', question: 'The first bicycle-like machine was invented in Germany.', options: { A: 'TRUE', B: 'FALSE', C: 'NOT GIVEN' }, answer: 'A', explanation: 'Invented by Baron Karl von Drais in Germany (para 1).' },
            { id: 2, type: 'mcq', question: "The 'dandy horse' had a basic chain system.", options: { A: 'TRUE', B: 'FALSE', C: 'NOT GIVEN' }, answer: 'B', explanation: 'The dandy horse had no pedals or chain system (para 1).' },
            { id: 3, type: 'mcq', question: 'Baron Karl von Drais became wealthy from his invention.', options: { A: 'TRUE', B: 'FALSE', C: 'NOT GIVEN' }, answer: 'C', explanation: 'The passage does not mention his wealth.' },
            { id: 4, type: 'mcq', question: "The 'boneshaker' was named after its rough ride.", options: { A: 'TRUE', B: 'FALSE', C: 'NOT GIVEN' }, answer: 'A', explanation: 'The name came from its rough ride on cobblestone roads (para 2).' },
            { id: 5, type: 'mcq', question: 'The penny-farthing was the safest bicycle of its time.', options: { A: 'TRUE', B: 'FALSE', C: 'NOT GIVEN' }, answer: 'B', explanation: 'They were fast but dangerous (para 2).' },
            { id: 6, type: 'mcq', question: 'John Kemp Starley was a professional athlete.', options: { A: 'TRUE', B: 'FALSE', C: 'NOT GIVEN' }, answer: 'C', explanation: 'The passage does not mention him being an athlete.' },
            { id: 7, type: 'mcq', question: 'Pneumatic tires improved the comfort of riding.', options: { A: 'TRUE', B: 'FALSE', C: 'NOT GIVEN' }, answer: 'A', explanation: 'Air-filled tires made cycling more comfortable (para 3).' },
            { id: 8, type: 'fill-blank', question: "The 'dandy horse' was constructed primarily of ___.", answer: 'WOOD', hint: '1 word' },
            { id: 9, type: 'fill-blank', question: 'Early wheels used ___ for the rims.', answer: 'IRON', hint: '1 word' },
            { id: 10, type: 'fill-blank', question: 'The Michaux design was the first to use ___.', answer: 'PEDALS', hint: '1 word' },
            { id: 11, type: 'fill-blank', question: "Starley's bike was called the ___ Bicycle.", answer: 'SAFETY', hint: '1 word' },
            { id: 12, type: 'fill-blank', question: 'The safety bicycle used a ___ to drive the rear wheel.', answer: 'CHAIN', hint: '1 word' },
            { id: 13, type: 'fill-blank', question: 'Dunlop invented tires filled with ___.', answer: 'AIR', hint: '1 word' },
          ],
        },
      ],
    },
    {
      id: 'passage2',
      title: 'Passage 2 - The Science of Laughter',
      instructions: 'Read the passage and answer questions 14-26.',
      type: 'passage',
      passages: [
        {
          title: 'The Science of Laughter',
          content: 'Laughter involves 15 facial muscles contracting and triggers the release of endorphins — the body\'s natural painkillers. This chemical response can help in relieving pain and stress.\n\nLaughter also reduces stress hormones like cortisol and adrenaline. By improving blood vessel function, it aids cardiovascular health. Some researchers compare laughter to "a mild workout" for the body.\n\nSocially, laughter serves as a signal of safety and playfulness. Evolutionary scientists believe laughter existed before language, acting as a social glue that strengthened bonds within groups. Laughter helps build social connections.',
          questions: [
            { id: 14, type: 'mcq', question: 'How many facial muscles contract during laughter?', options: { A: '15', B: '20', C: '25' }, answer: 'A', explanation: 'Laughter involves 15 facial muscles (para 1).' },
            { id: 15, type: 'mcq', question: 'What are endorphins?', options: { A: 'Stress hormones', B: 'Harmful chemicals', C: 'Natural painkillers' }, answer: 'C', explanation: 'Endorphins are the body\'s natural painkillers (para 1).' },
            { id: 16, type: 'mcq', question: 'Which hormone is reduced by laughter?', options: { A: 'Insulin', B: 'Cortisol', C: 'Melatonin' }, answer: 'B', explanation: 'Laughter reduces cortisol and adrenaline (para 2).' },
            { id: 17, type: 'mcq', question: 'How does laughter affect blood vessels?', options: { A: 'Constricts them', B: 'Improves their function', C: 'Has no effect' }, answer: 'B', explanation: 'Laughter improves blood vessel function (para 2).' },
            { id: 18, type: 'mcq', question: 'What is laughter compared to?', options: { A: 'Sleeping', B: 'A mild workout', C: 'Eating' }, answer: 'B', explanation: 'Researchers compare laughter to "a mild workout" (para 2).' },
            { id: 19, type: 'mcq', question: 'What is the evolutionary purpose of laughter?', options: { A: 'To hunt better', B: 'To find a mate', C: 'To signal safety' }, answer: 'C', explanation: 'Laughter serves as a signal of safety and playfulness (para 3).' },
            { id: 20, type: 'mcq', question: 'Laughter existed before which ability?', options: { A: 'Walking', B: 'Language', C: 'Making fire' }, answer: 'B', explanation: 'Laughter existed before language (para 3).' },
            { id: 21, type: 'fill-blank', question: 'Laughter triggers the brain to release ___.', answer: 'ENDORPHINS', hint: '1 word' },
            { id: 22, type: 'fill-blank', question: 'These chemicals can help in relieving ___.', answer: 'PAIN', hint: '1 word' },
            { id: 23, type: 'fill-blank', question: 'It also lowers stress hormones like ___.', answer: 'CORTISOL', hint: '1 word' },
            { id: 24, type: 'fill-blank', question: 'By increasing blood ___ flow, it aids cardiovascular health.', answer: 'VESSEL', hint: '1 word' },
            { id: 25, type: 'fill-blank', question: 'Laughing helps strengthen social ___.', answer: 'BONDS', hint: '1 word' },
            { id: 26, type: 'fill-blank', question: 'It serves as a social ___ in human groups.', answer: 'GLUE', hint: '1 word' },
          ],
        },
      ],
    },
    {
      id: 'passage3',
      title: 'Passage 3 - Vertical Farming',
      instructions: 'Read the passage and answer questions 27-40.',
      type: 'passage',
      passages: [
        {
          title: 'Vertical Farming: The Future of Agriculture',
          content: '[A] By 2050, the global population is expected to reach 10 billion. Traditional farming faces serious challenges including water scarcity, soil degradation, and climate change.\n\n[B] Vertical farms grow crops in stacked layers indoors, using 95% less water than traditional farms. No chemical pesticides are needed because the controlled environment prevents pests.\n\n[C] Building farms inside cities reduces food miles dramatically, lowering carbon emissions from transportation.\n\n[D] However, a major hurdle is high energy consumption. Vertical farms rely on LED lighting to replace sunlight.',
          questions: [
            { id: 27, type: 'fill-blank', question: 'Paragraph A: Choose the best heading.', answer: 'URBAN POPULATION GROWTH', hint: 'Resource efficiency / Energy challenges / Urban population growth / Benefits for city life' },
            { id: 28, type: 'fill-blank', question: 'Paragraph B: Choose the best heading.', answer: 'RESOURCE EFFICIENCY', hint: 'Resource efficiency / Energy challenges / Urban population growth / Benefits for city life' },
            { id: 29, type: 'fill-blank', question: 'Paragraph C: Choose the best heading.', answer: 'BENEFITS FOR CITY LIFE', hint: 'Resource efficiency / Energy challenges / Urban population growth / Benefits for city life' },
            { id: 30, type: 'fill-blank', question: 'Paragraph D: Choose the best heading.', answer: 'ENERGY CHALLENGES', hint: 'Resource efficiency / Energy challenges / Urban population growth / Benefits for city life' },
            { id: 31, type: 'fill-blank', question: 'Population will reach ___ by 2050.', answer: '10 BILLION', hint: 'number + unit' },
            { id: 32, type: 'fill-blank', question: 'Traditional farms face ___ scarcity.', answer: 'WATER', hint: '1 word' },
            { id: 33, type: 'fill-blank', question: 'Vertical farms grow crops in ___ layers.', answer: 'STACKED', hint: '1 word' },
            { id: 34, type: 'fill-blank', question: 'They use 95% less ___ than normal farms.', answer: 'WATER', hint: '1 word' },
            { id: 35, type: 'fill-blank', question: 'No chemical ___ are needed.', answer: 'PESTICIDES', hint: '1 word' },
            { id: 36, type: 'fill-blank', question: 'Building farms in cities reduces ___ miles.', answer: 'FOOD', hint: '1 word' },
            { id: 37, type: 'fill-blank', question: 'This lowering reduces carbon ___.', answer: 'EMISSIONS', hint: '1 word' },
            { id: 38, type: 'fill-blank', question: 'A major hurdle is high ___ consumption.', answer: 'ENERGY', hint: '1 word' },
            { id: 39, type: 'fill-blank', question: 'They rely on ___ lighting.', answer: 'LED', hint: 'abbreviation' },
            { id: 40, type: 'fill-blank', question: 'Vertical farming could be a pillar of ___ agriculture.', answer: 'SUSTAINABLE', hint: '1 word' },
          ],
        },
      ],
    },
  ],
}
