export default {
  id: 'ket-1',
  type: 'ket',
  title: 'A2 Key (KET)',
  duration: 100,
  parts: [
    {
      id: 'part1',
      title: 'Part 1: Short Messages',
      type: 'mcq',
      instructions: 'Read the messages and choose the correct answer.',
      questions: [
        { id: 1, type: 'mcq', question: "What does this sign mean? — NO BICYCLES AGAINST THE WINDOW PLEASE", options: {A: "You cannot park your bike here.", B: "You can only wash your bike here.", C: "You should put your bike inside."}, answer: "A", explanation: "The sign prohibits placing bicycles against the window." },
        { id: 2, type: 'mcq', question: "Hi Mom, can you pick me up after football practice? It finishes at 5 PM instead of 4 PM. Thanks, Tom.", options: {A: "Tom is going to be late.", B: "Tom needs his football kit.", C: "Tom wants to go to practice at 5 PM."}, answer: "A", explanation: "Practice finishes at 5 instead of 4, so Tom is late." },
        { id: 3, type: 'mcq', question: "☕ Cafe notice: 'Free drink with every large pizza ordered before 6 PM.' What is true?", options: {A: "You can get a cheap pizza after 6 PM.", B: "You don't pay for a drink if you buy a big pizza early.", C: "You get a free drink all day."}, answer: "B", explanation: "Free drink with large pizza when ordered before 6 PM." },
        { id: 4, type: 'mcq', question: "📱 Sarah: 'Jane, the concert starts at 7:30. Let's meet at the station at 6:45 and eat first.' What is Sarah's plan?", options: {A: "Have dinner before the concert.", B: "Go to the concert at 6:45.", C: "Meet at the concert hall."}, answer: "A", explanation: "Sarah wants to eat first, then go to the concert." },
        { id: 5, type: 'mcq', question: "🛍️ Special Offer: 'Buy 2 T-shirts, get the 3rd at half price.' What is the deal?", options: {A: "All T-shirts are half price.", B: "You pay full price for two and 50% for the next one.", C: "Buy 3 T-shirts and pay for 2."}, answer: "B", explanation: "Buy 2 at full price, 3rd at half price." },
        { id: 6, type: 'mcq', question: "📋 Library Notice: 'Please return all borrowed books by Friday. Late returns will incur a small fine.' What does the notice say?", options: {A: "You can return books over the weekend.", B: "There is no cost if you return books by Friday.", C: "You will have to pay money if you miss the deadline."}, answer: "C", explanation: "Late returns incur a fine." },
      ],
    },
    {
      id: 'part2',
      title: 'Part 2: Matching',
      type: 'mcq',
      instructions: 'Match each person with the correct description.',
      questions: [
        { id: 7, type: 'mcq', question: "🏟️ Best for team sports on weekday evenings?", options: {A: "The Blue Whale (swimming)", B: "Victory Sports (football/basketball)", C: "Sunrise Gym (opens 5AM)"}, answer: "B", explanation: "Victory Sports has football and basketball on weekdays." },
        { id: 8, type: 'mcq', question: "⏰ Opens very early in the morning?", options: {A: "The Blue Whale", B: "Victory Sports", C: "Sunrise Gym"}, answer: "C", explanation: "Sunrise Gym opens at 5 AM." },
        { id: 9, type: 'mcq', question: "🏊 Swimming classes with teachers?", options: {A: "The Blue Whale", B: "Victory Sports", C: "Sunrise Gym"}, answer: "A", explanation: "The Blue Whale has swimming classes for all levels." },
        { id: 10, type: 'mcq', question: "💰 No monthly fee required?", options: {A: "The Blue Whale", B: "Victory Sports", C: "Sunrise Gym"}, answer: "C", explanation: "Sunrise Gym charges per visit, no monthly fee." },
        { id: 11, type: 'mcq', question: "🚌 Located next to the bus station?", options: {A: "The Blue Whale", B: "Victory Sports", C: "Sunrise Gym"}, answer: "A", explanation: "The Blue Whale is near the bus station." },
        { id: 12, type: 'mcq', question: "🔓 Free lockers available?", options: {A: "The Blue Whale", B: "Victory Sports", C: "Sunrise Gym"}, answer: "B", explanation: "Victory Sports has free lockers." },
      ],
    },
    {
      id: 'part5',
      title: 'Part 5: Gapped Text',
      type: 'mcq',
      instructions: 'Choose the correct word to complete the sentence.',
      questions: [
        { id: 13, type: 'mcq', question: "Yesterday, I ___ to the cinema with my friends.", options: {A: "go", B: "went", C: "gone", D: "going"}, answer: "B", explanation: "Past tense needed for 'yesterday'." },
        { id: 14, type: 'mcq', question: "The movie was very ___. We enjoyed it a lot.", options: {A: "excited", B: "exciting", C: "bore", D: "boring"}, answer: "B", explanation: "'Exciting' describes the movie." },
        { id: 15, type: 'mcq', question: "She ___ to school every day.", options: {A: "walk", B: "walks", C: "walking", D: "walked"}, answer: "B", explanation: "Present simple, third person singular." },
        { id: 16, type: 'mcq', question: "There ___ some milk in the fridge.", options: {A: "is", B: "are", C: "have", D: "has"}, answer: "A", explanation: "'Milk' is uncountable, singular." },
        { id: 17, type: 'mcq', question: "I ___ like spicy food.", options: {A: "don't", B: "doesn't", C: "not", D: "no"}, answer: "A", explanation: "Negative present simple, first person." },
        { id: 18, type: 'mcq', question: "Can you ___ me the salt, please?", options: {A: "give", B: "pass", C: "take", D: "bring"}, answer: "B", explanation: "'Pass' is the correct verb for handing something." },
        { id: 19, type: 'mcq', question: "We ___ going to the beach tomorrow.", options: {A: "is", B: "am", C: "are", D: "be"}, answer: "C", explanation: "Present continuous with 'we'." },
        { id: 20, type: 'mcq', question: "He is the ___ boy in the class.", options: {A: "tall", B: "taller", C: "tallest", D: "most tall"}, answer: "C", explanation: "Superlative form." },
        { id: 21, type: 'mcq', question: "Please turn ___ the lights before leaving.", options: {A: "on", B: "off", C: "up", D: "down"}, answer: "B", explanation: "'Turn off' means to switch something off." },
        { id: 22, type: 'mcq', question: "We have lived here ___ 2015.", options: {A: "for", B: "since", C: "from", D: "in"}, answer: "B", explanation: "'Since' with a specific point in time." },
      ],
    },
    {
      id: 'part6',
      title: 'Part 6: Writing',
      type: 'mcq',
      instructions: 'Choose the correct sentence for each situation.',
      questions: [
        { id: 23, type: 'mcq', question: "You want to borrow your friend's pen. What do you say?", options: {A: "Give me your pen!", B: "Can I borrow your pen, please?", C: "I like your pen."}, answer: "B", explanation: "Polite request." },
        { id: 24, type: 'mcq', question: "Your friend looks tired. What do you say?", options: {A: "You look tired. Are you OK?", B: "Go to bed!", C: "I'm not tired."}, answer: "A", explanation: "Showing concern politely." },
        { id: 25, type: 'mcq', question: "You don't know the time. What do you ask?", options: {A: "What time is it?", B: "Tell me the time!", C: "Do you know time?"}, answer: "A", explanation: "Standard question about time." },
        { id: 26, type: 'mcq', question: "You need help with your homework. What do you say?", options: {A: "Do my homework!", B: "Can you help me with my homework, please?", C: "Homework is difficult."}, answer: "B", explanation: "Polite request for help." },
        { id: 27, type: 'mcq', question: "You want to invite your friend to a party. What do you say?", options: {A: "Come to my party!", B: "Would you like to come to my party?", C: "I'm having a party."}, answer: "B", explanation: "Polite invitation." },
        { id: 28, type: 'mcq', question: "You accidentally step on someone's foot. What do you say?", options: {A: "It's your fault.", B: "I'm sorry!", C: "Watch where you're going!"}, answer: "B", explanation: "Apologizing." },
      ],
    },
  ],
}
