export default {
  id: 'pet-1',
  type: 'pet',
  title: 'B1 Preliminary (PET)',
  duration: 120,
  parts: [
    {
      id: 'part1',
      title: 'Part 1: Thông báo (Questions 1-5)',
      type: 'mcq',
      instructions: 'Read the signs and messages. Choose the correct answer.',
      questions: [
        { id: 1, type: 'mcq', question: "Library Notice: Please return all borrowed books by Friday. Books returned late will incur a fine of £1 per day.", options: {A: "You must pay £1 to borrow a book on Friday.", B: "There is no charge for books returned after Friday.", C: "You will have to pay if you keep books longer than allowed."}, answer: "C", explanation: '"Incur a fine" = pay if keep longer.' },
        { id: 2, type: 'mcq', question: "Message from Sarah: Hi Jack, I've left my umbrella at your house. Could you bring it to the cinema tonight? If not, I'll come by tomorrow.", options: {A: "Sarah wants Jack to meet her at his house.", B: "Sarah hopes Jack can return her umbrella tonight.", C: "Jack should go to Sarah's house to get the umbrella."}, answer: "B", explanation: '"Could you bring it to the cinema tonight?" = hopes Jack returns umbrella tonight.' },
        { id: 3, type: 'mcq', question: "Gym Sign: Lockers are for daily use only. Items left overnight will be removed by staff.", options: {A: "You can keep your things in a locker as long as you want.", B: "Staff will take away anything found in lockers after the gym closes.", C: "You must use a locker if you have heavy items."}, answer: "B", explanation: '"Items left overnight will be removed."' },
        { id: 4, type: 'mcq', question: "Email to Students: The school trip to the museum is cancelled due to the bus strike. Classes will run as normal instead.", options: {A: "Students should go to the museum by themselves.", B: "There will be no school tomorrow because of the strike.", C: "Students must attend their usual lessons tomorrow."}, answer: "C", explanation: '"Classes will run as normal" = attend usual lessons.' },
        { id: 5, type: 'mcq', question: "Cafe Notice: Order your food at the counter. Drinks will be served at your table.", options: {A: "You need to wait for a waiter to take your food order.", B: "You pay for everything at the table.", C: "You must go to the counter to choose what you want to eat."}, answer: "C", explanation: '"Order food at the counter" = go to the counter to order.' },
      ],
    },
    {
      id: 'part2',
      title: 'Part 2: Nối thông tin (Questions 6-10)',
      type: 'mcq',
      instructions: 'Match each person with the correct holiday destination.',
      questions: [
        { id: 6, type: 'mcq', question: "Marco loves history and wants to visit ancient ruins. He prefers quiet places without many tourists and likes walking in nature.", options: {A: "Sun City", B: "Green Valley", C: "Old Port", D: "Rocky Peak", E: "Hidden Temple", F: "Blue Bay", G: "Fun World", H: "Forest Trails"}, answer: "E", explanation: "Hidden Temple — ancient ruins, quiet, long walk." },
        { id: 7, type: 'mcq', question: "Elena is looking for a beach holiday. She wants to try water sports like surfing and enjoys lively nightlife.", options: {A: "Sun City", B: "Green Valley", C: "Old Port", D: "Rocky Peak", E: "Hidden Temple", F: "Blue Bay", G: "Fun World", H: "Forest Trails"}, answer: "A", explanation: "Sun City — beach, windsurf, discos." },
        { id: 8, type: 'mcq', question: "The Smith family have two young children. They want a safe place with activities for kids, like a zoo or theme park.", options: {A: "Sun City", B: "Green Valley", C: "Old Port", D: "Rocky Peak", E: "Hidden Temple", F: "Blue Bay", G: "Fun World", H: "Forest Trails"}, answer: "G", explanation: "Fun World — theme park, water park, childcare." },
        { id: 9, type: 'mcq', question: "Hiroko is interested in art and architecture. She wants to visit famous museums and galleries during the day.", options: {A: "Sun City", B: "Green Valley", C: "Old Port", D: "Rocky Peak", E: "Hidden Temple", F: "Blue Bay", G: "Fun World", H: "Forest Trails"}, answer: "C", explanation: "Old Port — museums, art galleries, architecture." },
        { id: 10, type: 'mcq', question: "David wants to go to the mountains. He is an experienced climber and wants a challenge. He prefers small traditional villages.", options: {A: "Sun City", B: "Green Valley", C: "Old Port", D: "Rocky Peak", E: "Hidden Temple", F: "Blue Bay", G: "Fun World", H: "Forest Trails"}, answer: "D", explanation: "Rocky Peak — steepest climbs, stone houses." },
      ],
    },
    {
      id: 'part3',
      title: 'Part 3: Đọc hiểu (Questions 11-15)',
      type: 'mcq',
      instructions: 'Read the text and choose the correct answer.',
      questions: [
        { id: 11, type: 'mcq', question: "Jane decided to run a marathon because", options: {A: "She had always loved running.", B: "She wanted to prove she was an athlete.", C: "She was looking for a personal challenge.", D: "Her friends encouraged her to do it."}, answer: "C", explanation: 'After turning 30, she wanted a challenge.' },
        { id: 12, type: 'mcq', question: "How did Jane feel about her training?", options: {A: "It was easy from the very beginning.", B: "She saw a slow but steady improvement.", C: "She found it impossible to run for long.", D: "She trained for a year before the race."}, answer: "B", explanation: 'At first only 10 minutes, but gradually improved.' },
        { id: 13, type: 'mcq', question: "What happened at the 30-kilometer mark?", options: {A: "She decided to quit the race.", B: "She met a young boy who was running.", C: "She felt physical pain but found motivation.", D: "The weather became too cold to continue."}, answer: "C", explanation: 'Legs hurt but a boy with a sign gave her energy.' },
        { id: 14, type: 'mcq', question: "How did Jane feel when she finished?", options: {A: "Disappointed because she was slow.", B: "Happy to have beaten the other runners.", C: "Emotional because of her achievement.", D: "Relieved that the pain had finally stopped."}, answer: "C", explanation: 'She cried because she was so proud.' },
        { id: 15, type: 'mcq', question: "What would be a good title for Jane's blog?", options: {A: "How to win your first big race.", B: "From running hater to marathon finisher.", C: "The best training tips for young athletes.", D: "My painful experience in the cold weather."}, answer: "B", explanation: 'Best summary — hated running to completing a marathon.' },
      ],
    },
    {
      id: 'part4',
      title: 'Part 4: Điền câu (Questions 16-20)',
      type: 'mcq',
      instructions: 'Choose the correct sentence to fill each gap in the text about umbrellas.',
      questions: [
        { id: 16, type: 'mcq', question: "The first umbrellas were probably made to protect people from the sun, not the rain. ___ Ancient Egyptians used umbrellas made of feathers and palm leaves.", options: {A: "They were called parasols.", B: "They were very expensive.", C: "Only royalty could use them.", D: "They were made of wood."}, answer: "A", explanation: 'Parasol (para=against, sol=sun) explains the previous sentence about sun protection.' },
        { id: 17, type: 'mcq', question: "In ancient Greece and Rome, umbrellas were seen as a symbol of wealth and power. ___", options: {A: "They were decorated with gold and jewels.", B: "Only women could carry them.", C: "They were used only in temples.", D: "The poor made their own."}, answer: "A", explanation: 'Gold and jewels detail the wealth and power mentioned.' },
        { id: 18, type: 'mcq', question: "It wasn't until the 18th century that umbrellas became common in Europe for rain protection. Before that, people thought using an umbrella was a sign of weakness. ___", options: {A: "Women refused to use them.", B: "Men refused to carry them in public.", C: "Children were afraid of them.", D: "Kings banned them."}, answer: "B", explanation: 'Men refused to carry them — continues the idea of weakness.' },
        { id: 19, type: 'mcq', question: "Early European umbrellas were made of wood and heavy cloth, which made them very difficult to carry. ___", options: {A: "They were very beautiful.", B: "Only rich people owned them.", C: "They soon became lighter.", D: "They needed two hands to hold.", E: "People stored them in special cases.", F: "They were very expensive.", G: "They were so heavy that you needed two hands to hold them."}, answer: "G", explanation: '"Heavy... needed two hands" supports "difficult to carry".' },
        { id: 20, type: 'mcq', question: "Modern umbrellas are much lighter because they use materials like plastic and aluminum. ___ Today, you can find them in every color and size imaginable.", options: {A: "They have become an essential item.", B: "They are now very cheap.", C: "Most people own two umbrellas.", D: "They are made in factories."}, answer: "A", explanation: '"Essential item" bridges to the conclusion about all colors and sizes.' },
      ],
    },
    {
      id: 'part5',
      title: 'Part 5: Điền từ (Questions 21-26)',
      type: 'mcq',
      instructions: 'Choose the correct word to fill each gap.',
      questions: [
        { id: 21, type: 'mcq', question: "The Great Barrier Reef is the ___ coral reef system in the world.", options: {A: "largest", B: "longest", C: "highest", D: "deepest"}, answer: "A", explanation: 'Largest — most common phrase: the largest coral reef system.' },
        { id: 22, type: 'mcq', question: "This amazing place is ___ up of thousands of individual reefs.", options: {A: "put", B: "made", C: "kept", D: "set"}, answer: "B", explanation: 'Passive: "be made up of" = composed of.' },
        { id: 23, type: 'mcq', question: "It is so large that it can be ___ from outer space.", options: {A: "looked", B: "watched", C: "seen", D: "noticed"}, answer: "C", explanation: '"Seen from space" — look/watch need prepositions.' },
        { id: 24, type: 'mcq', question: "___ the reef is in danger because of climate change.", options: {A: "Although", B: "Because", C: "However", D: "Instead"}, answer: "C", explanation: '"However" at start of sentence with comma, contrasting the positive description.' },
        { id: 25, type: 'mcq', question: "The water is getting warmer, which ___ the coral.", options: {A: "hurts", B: "pains", C: "breaks", D: "destroys"}, answer: "A", explanation: 'Warmer water hurts/damages coral gradually.' },
        { id: 26, type: 'mcq', question: "We must ___ our best to protect this natural wonder.", options: {A: "make", B: "do", C: "give", D: "take"}, answer: "B", explanation: '"Do one\'s best" = try your hardest.' },
      ],
    },
    {
      id: 'part6',
      title: 'Part 6: Viết từ (Questions 27-32)',
      type: 'mcq',
      instructions: 'Write one word in each gap.',
      questions: [
        { id: 27, type: 'fill-blank', question: "Hi Chloe, How ___ you?", hint: "Question word for health", answer: "are" },
        { id: 28, type: 'fill-blank', question: "I'm writing to tell you ___ my new house.", hint: "Preposition", answer: "about" },
        { id: 29, type: 'fill-blank', question: "My room is much bigger ___ my old one.", hint: "Comparison word", answer: "than" },
        { id: 30, type: 'fill-blank', question: "I have a great view ___ the park from my window.", hint: "Preposition", answer: "of" },
        { id: 31, type: 'fill-blank', question: "Would you like to come and visit me ___ Saturday?", hint: "Preposition for day of week", answer: "on" },
        { id: 32, type: 'fill-blank', question: "My mum says she will cook a special dinner ___ us.", hint: "Preposition meaning 'for'", answer: "for" },
      ],
    },
  ],
}
